In [1]:
import numpy as np

In [2]:
myList = [1,2,3]

In [8]:
myMatrix = [[1,2,3],[4,5,6], [7,8,9]]

In [9]:
print(myList)

[1, 2, 3]


In [10]:
print(myMatrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [11]:
np.array(myList)

array([1, 2, 3])

In [12]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [25]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones(2)

array([1., 1.])

In [23]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [30]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.random.rand(3,3)

array([[0.03087347, 0.80901248, 0.55026119],
       [0.71349644, 0.89118096, 0.61263508],
       [0.62092657, 0.01206615, 0.8220254 ]])

In [34]:
np.random.randn(3,3)

array([[ 1.10449418,  0.41335642, -0.50926331],
       [ 0.16027865, -0.15253821, -1.28706562],
       [-0.32573669,  2.15974428, -0.54508884]])

In [40]:
np.random.randint(0,100)

38

In [41]:
np.random.randint(0,100,10)

array([89, 56,  4, 94, 28, 11, 74, 11, 71, 58])

In [44]:
arr = np.arange(25)

In [45]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [51]:
arr = arr.reshape(5,5)

In [52]:
i = np.eye(5)

In [53]:
print(arr * i)

[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]


In [54]:
print(i * arr)

[[ 0.  0.  0.  0.  0.]
 [ 0.  6.  0.  0.  0.]
 [ 0.  0. 12.  0.  0.]
 [ 0.  0.  0. 18.  0.]
 [ 0.  0.  0.  0. 24.]]


In [55]:
arr.max()

24

In [56]:
arr.min()

0

In [57]:
arr.argmax()

24

In [58]:
arr.argmin()

0

In [60]:
arr.shape

(5, 5)

In [61]:
arr.dtype

dtype('int32')

In [62]:
arr + arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [63]:
arr - arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [64]:
arr * arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [65]:
 arr - 100

array([[-100,  -99,  -98,  -97,  -96],
       [ -95,  -94,  -93,  -92,  -91],
       [ -90,  -89,  -88,  -87,  -86],
       [ -85,  -84,  -83,  -82,  -81],
       [ -80,  -79,  -78,  -77,  -76]])

In [66]:
np.sqrt(arr)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

In [67]:
np.exp(np.sqrt(arr))

array([[  1.        ,   2.71828183,   4.11325038,   5.65223367,
          7.3890561 ],
       [  9.35646902,  11.58243519,  14.09403011,  16.91882868,
         20.08553692],
       [ 23.62434292,  27.56714845,  31.94774551,  36.80196629,
         42.16782067],
       [ 48.08562838,  54.59815003,  61.7507194 ,  69.59137847,
         78.17101632],
       [ 87.54351246,  97.76588528, 108.898446  , 121.00495841,
        134.15280493]])

In [68]:
np.exp(arr)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
        1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10]])

In [69]:
np.max(arr)

24

In [70]:
np.min(arr)

0

In [71]:
np.sin(arr)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [73]:
np.cos(arr)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901]])

In [74]:
 np.arccos(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arccos
  """Entry point for launching an IPython kernel.


array([[1.57079633, 0.        ,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan]])

In [75]:
np.arcsin(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


array([[0.        , 1.57079633,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan,        nan]])

In [77]:
clear()

In [78]:
import pandas as pd

In [79]:
# SERIES

In [80]:
labels = ['a', 'b', 'c']

In [81]:
my_data = [10, 20, 30]

In [82]:
arr = np.array(my_data)

In [83]:
d = {'a':10, 'b':20, 'c':30}

In [84]:
pd.Series(data = my_data) 

0    10
1    20
2    30
dtype: int64

In [85]:
pd.Series(data = my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [86]:
pd.Series(my_data, labels)

a    10
b    20
c    30
dtype: int64

In [87]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [88]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [89]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [90]:
ser1 = pd.Series([1,2,3,4],['USA', 'Germany', 'India', 'Japan'])

In [91]:
ser2 = pd.Series([1,2,3,4],['China','Italy','Sri Lanka','Japan'])

In [92]:
ser3 = pd.Series(data=labels)

In [94]:
ser1 + ser2

China        NaN
Germany      NaN
India        NaN
Italy        NaN
Japan        8.0
Sri Lanka    NaN
USA          NaN
dtype: float64

In [95]:
# DATA FRAMES

In [96]:
np.random.seed(101)

In [97]:
df = pd.DataFrame(np.random.randn(5,4),['a','b','c','d','e'],['w','x','y','z'])

In [98]:
print(df)

          w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509


In [99]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [100]:
df['w']

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [101]:
df.w

a    2.706850
b    0.651118
c   -2.018168
d    0.188695
e    0.190794
Name: w, dtype: float64

In [102]:
df[['w','z']]

w         z
a  2.706850  0.503826
b  0.651118  0.605965
c -2.018168 -0.589001
d  0.188695  0.955057
e  0.190794  0.683509

In [103]:
type(df['w'])

pandas.core.series.Series

In [104]:
type(df)

pandas.core.frame.DataFrame

In [115]:
df['n'] = df['w'] + df['y']

In [106]:
df

w         x         y         z         n
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [108]:
df.drop('n',1)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [109]:
df

w         x         y         z         n
a  2.706850  0.628133  0.907969  0.503826  3.614819
b  0.651118 -0.319318 -0.848077  0.605965 -0.196959
c -2.018168  0.740122  0.528813 -0.589001 -1.489355
d  0.188695 -0.758872 -0.933237  0.955057 -0.744542
e  0.190794  1.978757  2.605967  0.683509  2.796762

In [116]:
df.drop('n',axis=1, inplace=True)

In [113]:
df.drop('e',axis=0)

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057

In [117]:
df

w         x         y         z
a  2.706850  0.628133  0.907969  0.503826
b  0.651118 -0.319318 -0.848077  0.605965
c -2.018168  0.740122  0.528813 -0.589001
d  0.188695 -0.758872 -0.933237  0.955057
e  0.190794  1.978757  2.605967  0.683509

In [119]:
df.loc['a']

w    2.706850
x    0.628133
y    0.907969
z    0.503826
Name: a, dtype: float64

In [120]:
df.iloc[1]

w    0.651118
x   -0.319318
y   -0.848077
z    0.605965
Name: b, dtype: float64

In [121]:
df.loc['b','y']

-0.8480769834036315

In [122]:
df.loc[['a','b'],['w','y']]

w         y
a  2.706850  0.907969
b  0.651118 -0.848077